<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h1 id="privacy-isnt-about-hiding"><a href="#privacy-isnt-about-hiding">Privacy isn’t about hiding</a></h1>
    <p>
      The &quot;I have nothing to hide&quot; argument frames privacy as something only criminals and other bad actors
      would demand, but nothing could be further from the truth. Privacy is about the <strong>freedom</strong>
      to make choices without fear: how you want to live, what you believe in, who you are friends with, and what you want
      to share with whom. A lack of privacy leads to uniformity and
      <strong>self-censorship</strong>
      , which pushes our opinions to the edges and erodes our ability to engage in healthy debate.
    </p>
    <p>
      Ultimately, privacy also protects us from the unknown. Circumstances change. Something that can be harmlessly
      shared today may <strong>someday</strong>
      be worth concealing, whether it’s political beliefs or your ethnic or religious background. Privacy is the
      <strong>ultimate insurance</strong>
      against a rapidly changing corporate and political climate.
    </p>
    <p>Once we lose our privacy, we won’t get it back.</p>
    <h1 id="privacy-is-a-human-right"><a href="#privacy-is-a-human-right">Privacy is a human right</a></h1>
    <p>
      Just like other human rights, we didn’t always have the right to privacy. Several dictatorships around the world
      still don&#39;t value this right. Generations before ours fought for our right to privacy. Not caring about it
      shows little knowledge about history and the importance of it.
    </p>
    <p>
      <strong>Article 12 of Universal Declaration of Human Rights</strong>
      states:
    </p>
    <blockquote>
      <p>
        No one shall be subjected to arbitrary interference with his privacy, family, home or correspondence, nor to
        attacks upon his honour and reputation.
      </p>
    </blockquote>
    <!-- Source: https://www.un.org/sites/un2.un.org/files/2021/03/udhr.pdf -->

    <p>
      It’s a <strong>human right</strong>
      just like the right to equality, to justice, freedom, a nationality, the right to religion, etc.
    </p>
    <h1 id="your-information-is-valuable"><a href="#your-information-is-valuable">Your information is valuable</a></h1>
    <p>
      You might be okay with governments or security agencies or companies having your private information. You might
      trust Google and Facebook. But what if these get hacked and your <strong>information</strong>
      falls in the
      <strong>wrong hands</strong>
      ? Let’s say, someone targeting your family, your company, your wife/husband. Would you still be okay with that? Would
      you be okay knowing that your photos, emails, or chats are in the hands of someone who can
      <strong>blackmail</strong>
      you? Can you imagine what it’s like to have your life torn apart because of a conversation you had 5 or 10 years ago?
      What would it be like to lose your job because of a conversation you had by phone with your wife?
    </p>
    <p>
      We’ve all joked with things we consider sensitive. But, among friends, it’s something we all do. In fact, <strong>
        our behavior changes depending on the people we’re with
      </strong>
      . I bet I could find something offensive you said in a group chat that you have with your closest friends. Because
      they’re your friends and it was a joke or a sarcastic remark. But take it out of context and it is not longer a joke.
      What would happen if this “joke” fell in the hands of someone trying to
      <strong>harm</strong>
      you?
    </p>
    <p>
      A company like Facebook or Google allows you to upload unlimited data to their servers, for free. What’s their
      business model?
      <strong>How do they make so much money?</strong>
      They
      <strong>sell your info</strong>
      to advertising companies. But they never asked you if you wanted to sell your information. If someone asked you in
      person 100 questions about your personal life to sell it, would you answer them? Probably not, right? But you let this
      happen every time you use a service that makes money by selling your info.
    </p>
  </article>
</Post>
