const a = /* @__PURE__ */ location.pathname.split("/").slice(0, -1).join("/"), f = [
  a + "/_app/immutable/entry/app.9d4bc23b.js",
  a + "/_app/immutable/assets/0.e5e8e962.css",
  a + "/_app/immutable/nodes/0.32413d4c.js",
  a + "/_app/immutable/nodes/1.88d83fdc.js",
  a + "/_app/immutable/assets/404.9de340c4.webp",
  a + "/_app/immutable/nodes/10.a38debcc.js",
  a + "/_app/immutable/nodes/11.673f7a4c.js",
  a + "/_app/immutable/assets/12.ab221059.css",
  a + "/_app/immutable/nodes/12.789c33ac.js",
  a + "/_app/immutable/nodes/13.74129492.js",
  a + "/_app/immutable/nodes/14.6a8384bb.js",
  a + "/_app/immutable/nodes/15.ceee7822.js",
  a + "/_app/immutable/nodes/16.bf8f84dc.js",
  a + "/_app/immutable/nodes/17.12d5a04f.js",
  a + "/_app/immutable/nodes/18.49c0d6bc.js",
  a + "/_app/immutable/nodes/19.db77cfb2.js",
  a + "/_app/immutable/assets/2.a3ec6066.css",
  a + "/_app/immutable/nodes/2.f53190ac.js",
  a + "/_app/immutable/nodes/3.b73a715c.js",
  a + "/_app/immutable/nodes/4.c1c127d0.js",
  a + "/_app/immutable/nodes/5.4a3d68f7.js",
  a + "/_app/immutable/nodes/6.3624235a.js",
  a + "/_app/immutable/nodes/7.2bf0f4de.js",
  a + "/_app/immutable/nodes/8.65373bb6.js",
  a + "/_app/immutable/assets/9.1ecd1937.css",
  a + "/_app/immutable/nodes/9.4627eb50.js",
  a + "/_app/immutable/assets/404.936a22c6.avif",
  a + "/_app/immutable/assets/AndThen.65d60ef0.css",
  a + "/_app/immutable/assets/HoverExplanation.dc6243ee.css",
  a + "/_app/immutable/chunks/AndThen.c7fd2454.js",
  a + "/_app/immutable/assets/right-arrow.3907c376.svg",
  a + "/_app/immutable/chunks/HoverExplanation.b14da956.js",
  a + "/_app/immutable/chunks/code_copy.64786281.js",
  a + "/_app/immutable/chunks/i18n-svelte.5393f767.js",
  a + "/_app/immutable/assets/avatar.9d2117a3.png",
  a + "/_app/immutable/assets/avatar.f6a08045.avif",
  a + "/_app/immutable/assets/avatar.ec2b368f.webp",
  a + "/_app/immutable/assets/avatar.3288fe50.jpeg",
  a + "/_app/immutable/assets/avatar.2149bba4.jpeg",
  a + "/_app/immutable/assets/avatar.fa6b069e.jpeg",
  a + "/_app/immutable/assets/avatar.df189fa7.jpeg",
  a + "/_app/immutable/assets/cover.ed3357af.webp",
  a + "/_app/immutable/chunks/image_banner.23c60a7b.js",
  a + "/_app/immutable/assets/404.3df25504.avif",
  a + "/_app/immutable/assets/avatar.d57963db.avif",
  a + "/_app/immutable/assets/avatar.79e8785a.avif",
  a + "/_app/immutable/assets/cover.591e2c0e.avif",
  a + "/_app/immutable/assets/cover.a1d7fd59.avif",
  a + "/_app/immutable/assets/cover.a3c999af.avif",
  a + "/_app/immutable/assets/github-mark.7a0dd11e.svg",
  a + "/_app/immutable/assets/cover.cc906006.avif",
  a + "/_app/immutable/assets/cover.0813ca5c.avif",
  a + "/_app/immutable/assets/cover.a9d2fd81.jpg",
  a + "/_app/immutable/assets/cover.35b15004.avif",
  a + "/_app/immutable/assets/cover.e48f9e2a.avif",
  a + "/_app/immutable/assets/cover.8da8655e.avif",
  a + "/_app/immutable/assets/cover.956594ec.jpg",
  a + "/_app/immutable/assets/cover.282e97a5.avif",
  a + "/_app/immutable/assets/cover.9987f033.avif",
  a + "/_app/immutable/assets/cover.9e9a75de.avif",
  a + "/_app/immutable/assets/cover.61c951a7.jpg",
  a + "/_app/immutable/assets/cover.7b45184c.avif",
  a + "/_app/immutable/assets/cover.ab1ce412.avif",
  a + "/_app/immutable/assets/cover.3c456421.avif",
  a + "/_app/immutable/assets/cover.45580095.jpg",
  a + "/_app/immutable/assets/cover.2d1ceeee.avif",
  a + "/_app/immutable/assets/semantic-elements.5dd718b4.avif",
  a + "/_app/immutable/assets/semantic-elements.257219cd.jpg",
  a + "/_app/immutable/assets/semantic-elements.4cc0cb17.avif",
  a + "/_app/immutable/assets/cover.b90ac14f.avif",
  a + "/_app/immutable/assets/cover.5b8fc453.avif",
  a + "/_app/immutable/assets/cover.e38f454b.jpg",
  a + "/_app/immutable/assets/cover.1ac84bc1.avif",
  a + "/_app/immutable/assets/cover.54e6ef07.avif",
  a + "/_app/immutable/assets/cover.30c387e0.avif",
  a + "/_app/immutable/assets/cover.c82b63c5.jpg",
  a + "/_app/immutable/assets/cover.be7f114b.avif",
  a + "/_app/immutable/assets/cover.20b76685.avif",
  a + "/_app/immutable/assets/cover.76630b80.avif",
  a + "/_app/immutable/assets/cover.b98f3e8c.jpg",
  a + "/_app/immutable/assets/cover.fd1a5cd5.avif",
  a + "/_app/immutable/assets/cover.0ffb5f23.avif",
  a + "/_app/immutable/assets/cover.45fd416f.avif",
  a + "/_app/immutable/assets/cover.ec8ca6f4.jpg",
  a + "/_app/immutable/assets/cover.c6f2ad72.avif",
  a + "/_app/immutable/assets/cover.047f793e.avif",
  a + "/_app/immutable/assets/cover.48a80b11.avif",
  a + "/_app/immutable/assets/cover.d0517d18.jpg",
  a + "/_app/immutable/assets/cover.4cfcd9d4.avif",
  a + "/_app/immutable/assets/cover.55c87cd8.avif",
  a + "/_app/immutable/assets/cover.df603fac.avif",
  a + "/_app/immutable/assets/cover.4efcf05d.jpg",
  a + "/_app/immutable/assets/cover.c2c14073.avif",
  a + "/_app/immutable/assets/cover.22952d01.avif",
  a + "/_app/immutable/assets/cover.f825a033.avif",
  a + "/_app/immutable/assets/cover.ff90d246.jpg",
  a + "/_app/immutable/assets/cover.5dc1e2b8.avif",
  a + "/_app/immutable/assets/cover.9a7164aa.avif",
  a + "/_app/immutable/assets/cover.f79a28c9.avif",
  a + "/_app/immutable/assets/cover.fc3c046a.jpg",
  a + "/_app/immutable/assets/cover.323502b0.avif",
  a + "/_app/immutable/assets/cover.4d6855f0.avif",
  a + "/_app/immutable/assets/cover.991a0e7d.jpg",
  a + "/_app/immutable/assets/cover.90111bc5.avif",
  a + "/_app/immutable/assets/cover.91ccd11b.avif",
  a + "/_app/immutable/assets/cover.ecc418a6.jpg",
  a + "/_app/immutable/assets/cover.548c4745.avif",
  a + "/_app/immutable/assets/cover.cdc31b4e.avif",
  a + "/_app/immutable/assets/cover.ddd54ba9.avif",
  a + "/_app/immutable/assets/cover.91123ef0.jpg",
  a + "/_app/immutable/assets/cover.68364fa9.avif",
  a + "/_app/immutable/assets/cover.6296ca24.avif",
  a + "/_app/immutable/assets/cover.766c0b7f.avif",
  a + "/_app/immutable/assets/cover.755ec32d.jpg",
  a + "/_app/immutable/assets/cover.78fbc872.avif",
  a + "/_app/immutable/chunks/index.5ccb46b4.js",
  a + "/_app/immutable/chunks/info_box.1f925e92.js",
  a + "/_app/immutable/chunks/post.1d4af444.js",
  a + "/_app/immutable/assets/post.20994fb9.css",
  a + "/_app/immutable/assets/KaTeX_AMS-Regular.0cdd387c.woff2",
  a + "/_app/immutable/assets/KaTeX_AMS-Regular.30da91e8.woff",
  a + "/_app/immutable/assets/KaTeX_AMS-Regular.68534840.ttf",
  a + "/_app/immutable/assets/KaTeX_Caligraphic-Bold.de7701e4.woff2",
  a + "/_app/immutable/assets/KaTeX_Caligraphic-Bold.1ae6bd74.woff",
  a + "/_app/immutable/assets/KaTeX_Caligraphic-Bold.07d8e303.ttf",
  a + "/_app/immutable/assets/KaTeX_Caligraphic-Regular.5d53e70a.woff2",
  a + "/_app/immutable/assets/KaTeX_Caligraphic-Regular.3398dd02.woff",
  a + "/_app/immutable/assets/KaTeX_Caligraphic-Regular.ed0b7437.ttf",
  a + "/_app/immutable/assets/KaTeX_Fraktur-Bold.74444efd.woff2",
  a + "/_app/immutable/assets/KaTeX_Fraktur-Bold.9be7ceb8.woff",
  a + "/_app/immutable/assets/KaTeX_Fraktur-Bold.9163df9c.ttf",
  a + "/_app/immutable/assets/KaTeX_Fraktur-Regular.51814d27.woff2",
  a + "/_app/immutable/assets/KaTeX_Fraktur-Regular.5e28753b.woff",
  a + "/_app/immutable/assets/KaTeX_Fraktur-Regular.1e6f9579.ttf",
  a + "/_app/immutable/assets/KaTeX_Main-Bold.0f60d1b8.woff2",
  a + "/_app/immutable/assets/KaTeX_Main-Bold.c76c5d69.woff",
  a + "/_app/immutable/assets/KaTeX_Main-Bold.138ac28d.ttf",
  a + "/_app/immutable/assets/KaTeX_Main-BoldItalic.99cd42a3.woff2",
  a + "/_app/immutable/assets/KaTeX_Main-BoldItalic.a6f7ec0d.woff",
  a + "/_app/immutable/assets/KaTeX_Main-BoldItalic.70ee1f64.ttf",
  a + "/_app/immutable/assets/KaTeX_Main-Italic.97479ca6.woff2",
  a + "/_app/immutable/assets/KaTeX_Main-Italic.f1d6ef86.woff",
  a + "/_app/immutable/assets/KaTeX_Main-Italic.0d85ae7c.ttf",
  a + "/_app/immutable/assets/KaTeX_Main-Regular.c2342cd8.woff2",
  a + "/_app/immutable/assets/KaTeX_Main-Regular.c6368d87.woff",
  a + "/_app/immutable/assets/KaTeX_Main-Regular.d0332f52.ttf",
  a + "/_app/immutable/assets/KaTeX_Math-BoldItalic.dc47344d.woff2",
  a + "/_app/immutable/assets/KaTeX_Math-BoldItalic.850c0af5.woff",
  a + "/_app/immutable/assets/KaTeX_Math-BoldItalic.f9377ab0.ttf",
  a + "/_app/immutable/assets/KaTeX_Math-Italic.7af58c5e.woff2",
  a + "/_app/immutable/assets/KaTeX_Math-Italic.8a8d2445.woff",
  a + "/_app/immutable/assets/KaTeX_Math-Italic.08ce98e5.ttf",
  a + "/_app/immutable/assets/KaTeX_SansSerif-Bold.e99ae511.woff2",
  a + "/_app/immutable/assets/KaTeX_SansSerif-Bold.ece03cfd.woff",
  a + "/_app/immutable/assets/KaTeX_SansSerif-Bold.1ece03f7.ttf",
  a + "/_app/immutable/assets/KaTeX_SansSerif-Italic.00b26ac8.woff2",
  a + "/_app/immutable/assets/KaTeX_SansSerif-Italic.91ee6750.woff",
  a + "/_app/immutable/assets/KaTeX_SansSerif-Italic.3931dd81.ttf",
  a + "/_app/immutable/assets/KaTeX_SansSerif-Regular.68e8c73e.woff2",
  a + "/_app/immutable/assets/KaTeX_SansSerif-Regular.11e4dc8a.woff",
  a + "/_app/immutable/assets/KaTeX_SansSerif-Regular.f36ea897.ttf",
  a + "/_app/immutable/assets/KaTeX_Script-Regular.036d4e95.woff2",
  a + "/_app/immutable/assets/KaTeX_Script-Regular.d96cdf2b.woff",
  a + "/_app/immutable/assets/KaTeX_Script-Regular.1c67f068.ttf",
  a + "/_app/immutable/assets/KaTeX_Size1-Regular.6b47c401.woff2",
  a + "/_app/immutable/assets/KaTeX_Size1-Regular.c943cc98.woff",
  a + "/_app/immutable/assets/KaTeX_Size1-Regular.95b6d2f1.ttf",
  a + "/_app/immutable/assets/KaTeX_Size2-Regular.d04c5421.woff2",
  a + "/_app/immutable/assets/KaTeX_Size2-Regular.2014c523.woff",
  a + "/_app/immutable/assets/KaTeX_Size2-Regular.a6b2099f.ttf",
  a + "/_app/immutable/assets/KaTeX_Size3-Regular.6ab6b62e.woff",
  a + "/_app/immutable/assets/KaTeX_Size3-Regular.500e04d5.ttf",
  a + "/_app/immutable/assets/KaTeX_Size4-Regular.a4af7d41.woff2",
  a + "/_app/immutable/assets/KaTeX_Size4-Regular.99f9c675.woff",
  a + "/_app/immutable/assets/KaTeX_Size4-Regular.c647367d.ttf",
  a + "/_app/immutable/assets/KaTeX_Typewriter-Regular.71d517d6.woff2",
  a + "/_app/immutable/assets/KaTeX_Typewriter-Regular.e14fed02.woff",
  a + "/_app/immutable/assets/KaTeX_Typewriter-Regular.f01f3e87.ttf",
  a + "/_app/immutable/chunks/scheduler.b261eb3c.js",
  a + "/_app/immutable/chunks/singletons.2a1643df.js",
  a + "/_app/immutable/chunks/timeFormat.04e1dbfb.js",
  a + "/_app/immutable/chunks/tippy.5f4e22e7.js",
  a + "/_app/immutable/assets/tippy.7df0e90e.css",
  a + "/_app/immutable/entry/start.79f53b3a.js"
], u = [
  a + "/.nojekyll",
  a + "/create-your-first-bot/botfather.mp4",
  a + "/favicon.ico",
  a + "/favicon.png",
  a + "/robots.txt",
  a + "/~partytown/debug/partytown-atomics.js",
  a + "/~partytown/debug/partytown-media.js",
  a + "/~partytown/debug/partytown-sandbox-sw.js",
  a + "/~partytown/debug/partytown-sw.js",
  a + "/~partytown/debug/partytown-ww-atomics.js",
  a + "/~partytown/debug/partytown-ww-sw.js",
  a + "/~partytown/debug/partytown.js",
  a + "/~partytown/partytown-atomics.js",
  a + "/~partytown/partytown-media.js",
  a + "/~partytown/partytown-sw.js",
  a + "/~partytown/partytown.js"
], _ = [
  a + "/",
  a + "/7-reasons-i-love-hetzner",
  a + "/ai-taking-our-jobs",
  a + "/atom.xml",
  a + "/barcodes-vs-qr-codes",
  a + "/boost-your-seo",
  a + "/choose-your-linux-shell",
  a + "/cloudflare-lava-lamps",
  a + "/create-an-echo-bot",
  a + "/create-your-first-bot",
  a + "/custom-email-with-cloudflare-and-gmail",
  a + "/feed.json",
  a + "/manifest.webmanifest",
  a + "/passwords-best-practices",
  a + "/privacy-policy",
  a + "/privacy-tips",
  a + "/sitemap.xml",
  a + "/technology-impact-on-the-environment",
  a + "/the-evolution-of-http",
  a + "/typescript-is-not-a-programming-language",
  a + "/versions.json",
  a + "/why-care-about-privacy",
  a + "/zip-bombs"
], c = "1716143709984", p = self, l = `cache${c}`, o = f.concat(u).concat(_), r = new Set(o);
p.addEventListener("install", (e) => {
  e.waitUntil(
    caches.open(l).then((s) => s.addAll(o)).then(() => {
      p.skipWaiting();
    })
  );
});
p.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys().then(async (s) => {
      for (const t of s)
        t !== l && await caches.delete(t);
      p.clients.claim();
    })
  );
});
async function n(e) {
  const s = await caches.open(`offline${c}`);
  try {
    const t = await fetch(e);
    return s.put(e, t.clone()), t;
  } catch (t) {
    const m = await s.match(e);
    if (m)
      return m;
    throw t;
  }
}
p.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET" || e.request.headers.has("range"))
    return;
  const s = new URL(e.request.url), t = s.protocol.startsWith("http"), m = s.hostname === self.location.hostname && s.port !== self.location.port, i = s.host === self.location.host && r.has(s.pathname), b = e.request.cache === "only-if-cached" && !i;
  t && !m && !b && e.respondWith(
    (async () => i && await caches.match(e.request) || n(e.request))()
  );
});
