<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h1 id="introduction"><a href="#introduction">Introduction</a></h1>
    <p>
      This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
      information when You use the Service and tells You about Your privacy rights and how the law protects You.
    </p>
    <p>
      We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection
      and use of information in accordance with this Privacy Policy.
    </p>
    <h1 id="interpretation-and-definitions">
      <a href="#interpretation-and-definitions">Interpretation and Definitions</a>
    </h1>
    <h2 id="interpretation"><a href="#interpretation">Interpretation</a></h2>
    <p>
      The words of which the initial letter is capitalized have meanings defined under the following conditions. The
      following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
    </p>
    <h2 id="definitions"><a href="#definitions">Definitions</a></h2>
    <p>For the purposes of this Privacy Policy:</p>
    <ul>
      <li>
        <p>
          <strong>Company</strong>
          (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement)
          refers to Sebastiano Racca&#39;s Blog.
        </p>
      </li>
      <li>
        <p>
          <strong>Device</strong>
          means any device that can access the Service such as a computer, a cellphone or a digital tablet.
        </p>
      </li>
      <li>
        <p>
          <strong>Personal Data</strong>
          is any information that relates to an identified or identifiable individual.
        </p>
      </li>
      <li>
        <p>
          <strong>Service</strong>
          refers to the Website.
        </p>
      </li>
      <li>
        <p>
          <strong>Service Provider</strong>
          means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies
          or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company,
          to perform services related to the Service or to assist the Company in analyzing how the Service is used.
        </p>
      </li>
      <li>
        <p>
          <strong>Usage Data</strong>
          refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure
          itself (for example, the duration of a page visit).
        </p>
      </li>
      <li>
        <p>
          <strong>Website</strong>
          refers to Sebastiano Racca&#39;s Blog, accessible from
          <a href="https://blog.racca.me" rel="external">https://blog.racca.me</a>
        </p>
      </li>
      <li>
        <p>
          <strong>You</strong>
          means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such
          individual is accessing or using the Service, as applicable.
        </p>
      </li>
    </ul>
    <h1 id="collecting-and-using-your-personal-data">
      <a href="#collecting-and-using-your-personal-data">Collecting and Using Your Personal Data</a>
    </h1>
    <p>This section outlines how Your Personal Data is collected and used when You access or use the Service.</p>
    <p>
      While the Company, Sebastiano Racca&#39;s Blog, does not personally collect any data, it&#39;s important to note
      that third-party services, such as GitHub Pages and Cloudflare, are utilized to provide and enhance the Service.
      These third-party services may collect certain information automatically when You interact with the Website.
      Please refer to the privacy policies of GitHub Pages and Cloudflare for details on their data collection and
      processing practices.
    </p>
    <h2 id="purpose-of-data-collection"><a href="#purpose-of-data-collection">Purpose of Data Collection</a></h2>
    <p>
      The primary purpose of collecting and using Your Personal Data is to ensure the proper functioning and improvement
      of the Service. The Company does not use cookies directly; however, third-party services may use cookies for
      various purposes, including web analytics.
    </p>
    <h2 id="service-providers"><a href="#service-providers">Service Providers</a></h2>
    <p>
      The Company may employ third-party companies or individuals (&quot;Service Providers&quot;) to facilitate the
      Service, provide the Service on behalf of the Company, perform services related to the Service, or assist the
      Company in analyzing how the Service is used. These Service Providers may have access to Your Personal Data only
      to perform these tasks on Our behalf and are obligated not to disclose or use it for any other purpose.
    </p>
    <h2 id="usage-data"><a href="#usage-data">Usage Data</a></h2>
    <p>
      Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service
      infrastructure itself. This may include the duration of a page visit, but the Company does not personally analyze
      or process this data.
    </p>
    <h2 id="your-rights"><a href="#your-rights">Your Rights</a></h2>
    <p>
      As an individual accessing or using the Service, You have rights regarding Your data. Even though the Company does
      not directly collect Personal Data, You may refer to the privacy policies of GitHub Pages and Cloudflare for
      information on how to exercise Your rights with respect to the data they may collect.
    </p>
    <h1 id="children-and-39-s-privacy"><a href="#children-and-39-s-privacy">Children&#39;s Privacy</a></h1>
    <p>
      Our Service does not address anyone under the age of 13. If You are a parent or guardian and You are aware that
      Your child has provided Us with Personal Data, please contact Us.
    </p>
    <h1 id="changes-to-this-privacy-policy">
      <a href="#changes-to-this-privacy-policy">Changes to This Privacy Policy</a>
    </h1>
    <p>
      This Privacy Policy may be updated to reflect changes in Our data practices, applicable laws, or to address new
      concerns. The date of the last update will be indicated at the beginning of the Privacy Policy. Significant
      changes will be notified to users through appropriate means. You are advised to review this Privacy Policy
      periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
    </p>
    <h1 id="contact-us"><a href="#contact-us">Contact Us</a></h1>
    <p>If you have any questions about this Privacy Policy, You can contact us:</p>
    <ul>
      <li>
        By email: <a href="mailto:sebastiano@racca.me">sebastiano@racca.me</a>
      </li>
      <li>
        By visiting this page on our website: <a href="https://racca.me/contact" rel="external">
          https://racca.me/contact
        </a>
      </li>
    </ul>
  </article>
</Post>
