<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import AndThen from '$custom/AndThen.svelte';
  import NotEmail from '$custom/NotEmail.svelte';
</script>

<Post>
  <article slot="post_content">
    <h1 id="create-a-custom-email-address-for-free">
      <a href="#create-a-custom-email-address-for-free">Create a Custom Email Address for Free</a>
    </h1>
    <p>
      In the digital age, having a custom email address not only adds a professional touch to your communication but
      also enhances brand identity. In this tutorial, we&#39;ll walk you through the process of setting up a custom
      email address using Cloudflare Email Routing and Gmail SMTP. By the end of this guide, you&#39;ll be able to send
      and receive emails using your own domain, all while leveraging the power and reliability of Gmail.
    </p>
    <h2 id="prerequisites"><a href="#prerequisites">Prerequisites</a></h2>
    <p>Before we dive into the steps, make sure you have the following prerequisites in place:</p>
    <ul>
      <li>An active Gmail account.</li>
      <li>A domain registered with Cloudflare.</li>
      <li>Access to your domain&#39;s DNS settings on Cloudflare.</li>
    </ul>
    <h1 id="setup-your-google-account"><a href="#setup-your-google-account">Setup Your Google Account</a></h1>
    <h2 id="enable-2-factor-authentification">
      <a href="#enable-2-factor-authentification">Enable 2 Factor Authentification</a>
    </h2>
    <p>If you already have enabled two factor authentification you can safely skip this step.</p>
    <ol>
      <li>
        Open your <a href="https://myaccount.google.com/" rel="external">Google Account</a>
        ;
      </li>
      <li>Select &quot;Security&quot; in the navigation panel;</li>
      <li>Under “Signing in to Google,” select&quot; 2-Step Verification&quot;, then &quot;Get started&quot;;</li>
      <li>Follow the on-screen steps.</li>
    </ol>
    <h2 id="create-an-app-password"><a href="#create-an-app-password">Create an App Password</a></h2>
    <p>
      An app password is a 16-digit passcode that gives a less secure app or device permission to access your Google
      Account.
    </p>
    <ol>
      <li>
        Open the <a href="https://myaccount.google.com/apppasswords" rel="external">App Passwords console</a>
        on your Google account;
      </li>
      <li>
        Type a name for your applicatiom <em>i.e. &quot;My Custom Email&quot;</em>
      </li>
      <li>Safely store the 16-digit passcode, you&#39;ll need this later.</li>
    </ol>
    <h1 id="enable-cloudflare-and-39-s-email-routing">
      <a href="#enable-cloudflare-and-39-s-email-routing">Enable Cloudflare&#39;s Email Routing</a>
    </h1>
    <p>
      Emails that are routed through Cloudflare to your preferred email inbox, benefit from enhanced security, spam
      filtering, and improved deliverability. Cloudflare Email Routing acts as a protective layer for your email
      infrastructure, shielding it from potential threats and optimizing the overall email experience.
    </p>
    <ol>
      <li>
        Go to the <strong><a href="https://dash.cloudflare.com" rel="external">Cloudflare Dashboard</a></strong>
        and select your domain;
      </li>
      <li>
        Go to <strong>Email</strong>
        <AndThen />
        <strong>Email Routing</strong>
        <AndThen text="then select" />
        <strong>Get Started</strong>
        ;
      </li>
      <li>
        Enter the custom email address in <strong>Custom Address</strong>
        (
        <em>i.e. <NotEmail email="cool-email@example.com" /></em>
        );
      </li>
      <li>
        Enter the email address you want your emails to be forwarded to in <strong>Destination Address</strong>
        (
        <em>i.e. <NotEmail email="my-personal-email@gmail.com" /></em>
        );
      </li>
      <li>
        Select <strong>Create and Continue</strong>
        <AndThen /> follow the instruction sent to your gmail address.
      </li>
      <li>
        Go to the <strong>DNS</strong>
        section of the dashboard and add a new TXT record with the following content:
      </li>
    </ol>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-txt">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">"v=spf1 include:_spf.mx.cloudflare.net include:_spf.google.com ~all"</div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <h1 id="add-your-cloudflare-routed-email-to-gmail">
      <a href="#add-your-cloudflare-routed-email-to-gmail">Add Your Cloudflare-Routed Email to Gmail</a>
    </h1>
    <p>Once did all the previous we can finally add the custom address to gmail.</p>
    <ol>
      <li>
        Go to your <a href="https://gmail.com/" rel="external">Gmail Account</a>
        <AndThen text="then click on" />
        <strong>Settings</strong>
        <AndThen text="then select" />
        <strong>Accounts</strong>
        ;
      </li>
      <li>
        Select <strong>Add another email address</strong>
        under
        <strong>Send Mail As</strong>
        ;
      </li>
      <li>
        Fill the form with the name of the email and the Cloudflare-routed email (
        <em>i.e. <NotEmail email="cool-email@example.com" /></em>
        ) <AndThen /> untick &quot;
        <strong>Treat as an alias</strong>
        &quot;;
      </li>
      <li>
        Fill the next form with the following information:
        <br />
        <strong>SMTP Server</strong>
        : smtp.gmail.com
        <br />
        <strong>Port</strong>
        : 587
        <br />
        <strong>Username</strong>
        : your gmail address (
        <em>i.e. <NotEmail email="my-personal-email@gmail.com" /></em>
        )
        <br />
        <strong>Password</strong>
        :
        <a href="#create-an-app-password">the app password</a>
      </li>
      <li>
        Leave <strong>TLS</strong>
        enabled <AndThen /> click
        <strong>Add Account</strong>
      </li>
      <li>Confirm the email address with the code Google&#39;s sent you to your gmail account.</li>
    </ol>
    <h1 id="enjoy"><a href="#enjoy">Enjoy</a></h1>
    <p>
      You now have a fully working email that is routed through Cloudflare to receive emails and uses Google&#39;s SMTP
      server to send them.
    </p>
    <p>Whenever you send a new email via GMail, make sure to switch the sender accordingly to your preferences.</p>
  </article>
</Post>
